max_players: 100
game_token: "replace w/ mint"
spawn_claim_multiplier: 1.1
tokens_minted: 50000
max_score: 500

mapmeta: 
  max_x: 8
  max_y: 8

spawns:
  -
    x: 0
    y: 0
    cost: 10
    clan: Ancients
  -
    x: 7
    y: 0
    cost: 10
    clan: Wildings
  -
    x: 0
    y: 7
    cost: 10
    clan: Creepers
  -
    x: 7
    y: 7
    cost: 10
    clan: Synths
  
structures: 
  - 
    x: 1
    y: 1
    structure_blueprint: "Meteor"
  - 
    x: 4
    y: 4
    structure_blueprint: "Meteor"
  - 
    x: 6
    y: 6
    structure_blueprint: "Meteor"